version: '3.8' 

services: # Serviços sendo executados
  db: #1 -  serviço de banco 
    image: mysql
    container_name: db
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=decoracao
      - MYSQL_ROOT_PASSWORD=1234

  pphpmyadmin:  #2 - PHPMYADMIN
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db

volumes:
  db: